### PR TITLE
[fix/1.x] Prioritize SOKETI_* variables over others.

### LINKED ISSUE #340: [bug] Prioritize `SOKETI_*` variables over others.
I would like to suggest using SOKETI_ for environment variables as your current variables some times conflict with existing ones.
For example, I use Beanstalk for a queue in Laravel to processing some heavy jobs. Soketi sees that and fails. Instead, I have to alter my Laravel queue.php file and change QUEUE_DRIVER to something like LARAVEL_QUEUE_DRIVER.

Of course, it works and is easy to change in my case, but might be avoidable with SOKETI_ distinction.

### PR DESCRIPTION
**Pull request by rolandstarke**
Closes #340 #453

So that if you have the following env:

```env
DEBUG=0
SOKETI_DEBUG=1
```

`SOKETI_DEBUG` wins.

### CODE REVIEW

File: src/cli/cli.ts [hunk 1]
```diff
@@ -136,7 +136,7 @@ export class Cli {
         require('dotenv').config();
 
         for (let envVar in this.envVariables) {
-            let value = process.env[envVar] || process.env[`SOKETI_${envVar}`] || null;
```
Comment (rennokki) [inline src/cli/cli.ts:139]: I think I'll prepare for 1.x by not taking into account any non-`SOKETI_` prefixed variable. One of the issues can be this: https://github.com/soketi/soketi/issues/453, where having an .env that may contain Soketi environments by accident (in this case `CACHE_DRIVER`) would lead to issues.

I think we should take into account just `SOKETI_*` variables. `master` branch will become 1.x

**Comment by 99linesofcode** [comment]
This is rather implicit and could be more clearly documented. Had to go through the history for `cli.ts` in order to find out why laravel/sail uses the `SOKETI_*` prefix while there is no mention of that in the documentation or the `cli.ts` itself.
