### PR TITLE
[FIX] Changing cache channel implementaion to match the pusher protocol.

### LINKED ISSUE #710: [BUG] Incorrect cache channel implementation
**Description**
How the cache channel is supposed to work - https://pusher.com/docs/channels/using_channels/cache-channels/
The following is the soketi behaviour.
1) The soketi implementaion does not fire the pusher:cache_miss event when the cache is empty. Only the webhook is triggered.
2) The soketi implementaion fires the pusher:cache_miss event with cached value as data, when data is available in cache. Which is wrong, the pusher:cache_miss event should only be fired when data is unavailable in cache.
3) The soketi implementaion does not fire the last sent event on the cache channel when data is available in the cache.

**Environment**
- Soketi version : 1.4.16
- Adapter : redis
- App Manager : array
- Queue : sync
- Cache Managers : redis

**Additional Information**
The below are the parts of code which are causing the issue
https://github.com/soketi/soketi/blob/1.x/src/http-handler.ts#L377-L395
https://github.com/soketi/soketi/blob/1.x/src/ws-handler.ts#L698-L706

I'm happy to fix the issue and provide a pull request with tests. Could you tell me the branch against which I should write the fix.

Thanks

### LINKED ISSUE #935: [BUG] uWS.js supports only Node.js 14, 16 and 18
is there any way to support Node 20

### PR DESCRIPTION
**Pull request by mlnkrish**
Fixes #710
Fixes #935

- Changed the cache key to "app:${app_id}:channel:${channel_id}:cache"
- Send pusher:cache_miss event without any data to the client when the cache is empty
- Send the cached event when the cache is not empty
- Not sending the pusher:cache_miss event when the cache is not empty
- Added Tests

### CODE REVIEW

File: src/http-handler.ts [hunk 1]
```diff
@@ -386,7 +386,7 @@ export class HttpHandler {
 
             if (Utils.isCachingChannel(channel)) {
                 this.server.cacheManager.set(
-                    `app:${appId}:channel:${channel}:cache_miss`,
+                    `app:${appId}:channel:${channel}:cache`,
```
Comment (rennokki) [inline src/http-handler.ts:389]: I would rather keep the key the same. Existing users that use it already and upgrade to the version containing this change might run into cache_miss not being fired because of the new changed key.

**Review by rennokki — CHANGES_REQUESTED** [review]

File: src/http-handler.ts (hunk 1 above)
Comment (mlnkrish) [reply src/http-handler.ts]: I have added a commit that keeps the key as cache_miss.

**Comment by rennokki** [comment]
@mlnkrish Can you allow me to edit the PR for formatting and fix the pipelines? Instructions here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by mlnkrish** [comment]
> @mlnkrish Can you allow me to edit the PR for formatting and fix the pipelines? Instructions here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

hello, sorry the e-mail got buried in my inbox. The fork lives under an organization, so there is no option to "Allow edits from maintainers". I have given you write access to the firked repository(https://github.com/chobiwa/soketi), does this help?

**Comment by FugiTech** [comment]
@rennokki Is there anything I can do to help move this forward? It'd be extremely useful for the projects I'm currently working on

**Comment by Zakini** [comment]
@rennokki Anything I can do to help with this too? I'm in the same situation as @FugiTech, cache channels would help a lot in a project I'm working on

**Comment by chrispage1** [comment]
How far away do you think we are with this one? Would be a good update to see live :)

Chris.

**Comment by zakini** [comment]
@rennokki is there anything I can do to help with getting a release out that includes this PR? Maybe I test out the release candidate (head of 1.x branch?) on my project?
